[server]
enableStaticServing = true

[[theme.fontFaces]]
family="marianne"
url="app/static/Marianne-Regular.otf"
style="normal"
weight=400
[[theme.fontFaces]]
family="marianne"
url="app/static/Marianne-Bold.otf"
style="nprmal"
weight=700
[[theme.fontFaces]]
family="marianne"
url="app/static/Marianne-Regularitalic.otf"
style="italic"
weight=400
[[theme.fontFaces]]
family="marianne"
url="app/static/Marianne-Bolditalic.otf"
style="italic"
weight=700

[theme]
font="marianne"
base="light"
primaryColor="#EF7757"

[theme.sidebar]
backgroundColor="#FEF2EF"